### ISSUE TITLE
Is not possible to rate

### ISSUE THREAD

**Issue by rootlinux2** [Belzee10/front10-rating#2]
This component doesn't allow to rate for more opinions is only possible to show the result but how can I get the users opinions?
I should be able to use this component to collect the user's opinions too, like an ON/OFF props.

Thanks!

**Comment by Belzee10** [comment]
Thanks, I'm working on it ;)

**Comment by rootlinux2** [comment]
Hi @Belzee10 
I just create a PR #3  where I create the feature of rate. In the other hand, I also create a PR #4 where I put some code to test your component.
